### ISSUE TITLE
Kasus widget selectInput    

### ISSUE THREAD

**Issue by alfanugraha** [Kelompok3MDS2023/Data-Base-Ruangan-IPB#4]
Ini contoh line yang bisa diperbaiki ya.. (dan line lain dengan kasus yang sama)

https://github.com/Kelompok3MDS2023/Data-Base-Ruangan-IPB/blob/0390c4f4d66b4b11bac452e95676f4d01f1c465c/ui.R#L302-L309

Jadi, blok widgetnya dimasukan ke dalam argumen `card_body_fill` biar tampilan yang muncul penuh tidak terpotong

```
grid_card(
  area = "area1",
  card_body_fill(
    selectInput(
      inputId = "listProdi_Jadwal",
      label = "Program Studi",
      choices = listProdi
    )
  )
),
```

**Comment by madsyauu** [comment]
alhamdulillah makasih banyakk bangg hehe
